---
name: GitHub Actions
on: push
jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2  # checkout v2.x.x (latest version)

        # Now that this repo gets fetched, this should work.
      - name: Build
        run: ./build.sh
